FROM alpine:3.14
RUN apk add --no-cache git make musl-dev go

# Configure Go
ENV GOROOT /usr/lib/go
ENV GOPATH /go
ENV PATH /go/bin:$PATH

RUN mkdir -p ${GOPATH}/src ${GOPATH}/bin
# Configure nodejs
RUN apk add --update nodejs yarn

WORKDIR /app 

RUN apk --no-cache add curl

# Install air
RUN curl -fLo install.sh https://raw.githubusercontent.com/cosmtrek/air/master/install.sh \
    && chmod +x install.sh && sh install.sh && cp ./bin/air /bin/air
    
# Install godotenv
RUN go install github.com/joho/godotenv/cmd/godotenv@latest

# Install npx
RUN yarn global add npx

# Install g++
RUN apk add --update alpine-sdk
RUn apk add libffi-dev openssl-dev
RUn apk --no-cache --update add build-base

CMD ["make", "build"]